#单机配置
server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  #    hostname: 192.168.110.9
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#集群配置
#server:
#  port: 7001
#eureka:
#  instance:
#    hostname: fenjin.eureka7001.com
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://fenjin.eureka7002.com:7002/eureka/,http://fenjin.eureka7003.com:7003/eureka/

#hosts文件中fenjin eureka集群配置主机访问地址
#  127.0.0.1       fenjin.eureka7001.com
#  127.0.0.1       fenjin.eureka7002.com
#  127.0.0.1       fenjin.eureka7003.com