server:
  port: 7010

spring:
  application:
    name: fenjin-cloud-feign-hystrix #微服务名称

#配置服务降级熔断
feign:
  hystrix:
    enabled: true

#配置通过注册中心访问微服务
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://fenjin.eureka7001.com:7001/eureka/,http://fenjin.eureka7002.com:7002/eureka/,http://fenjin.eureka7003.com:7003/eureka/
  instance:
    instance-id: fenjin-cloud-feign-hystrix-7010
    prefer-ip-address: true

info:
  app.name: fenjin-cloud-feign-hystrix-7010
  company.name: www.fenjin.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$