server:
  port: 7040

spring:
  application:
    name: fenjin-cloud-zuul-gateway

#配置通过注册中心访问微服务
eureka:
  client:
    service-url:
      defaultZone: http://fenjin.eureka7001.com:7001/eureka/,http://fenjin.eureka7002.com:7002/eureka/,http://fenjin.eureka7003.com:7003/eureka/
  instance:
    instance-id: fenjin-cloud-zuul-gateway-7040
    prefer-ip-address: true

  #hosts文件添加：127.0.0.1       fenjin.gateway.com
  #访问微服务地址：http://fenjin.gateway.com:7040/fenjin-fjtms-users/user/list
  #隐藏后的访问地址：http://fenjin.gateway.com:7040/fjtms/user/list

zuul:
  ignored-services: "*" #忽略路径
  routes:
    fenjin.serviceId: fenjin-cloud-feign-hystrix
    fenjin.path: /fjtms/**


info:
  app.name: fenjin-cloud-zuul-gateway
  company.name: www.fenjin.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


