server:
  port: 7040

spring:
  application:
    name: fenjin-cloud-zuul-gateway

#配置通过注册中心访问微服务
eureka:
  client:
    service-url:
#      defaultZone: http://192.168.110.9:7001/eureka/
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: fenjin-cloud-zuul-gateway-7040
#    hostname: 192.168.110.9
    prefer-ip-address: true

  #hosts文件添加：127.0.0.1       fenjin.gateway.com
  #访问微服务地址：http://fenjin.gateway.com:7040/fenjin-fjtms-users/user/list
  #隐藏后的访问地址：http://fenjin.gateway.com:7040/fjtms/user/list

zuul:
  ignored-services: "*" #忽略路径
  routes:
    users:
      serviceId: fenjin-fjtms-users
      path: /users/**
      strip-prefix: true
      sensitiveHeaders: "*"
    auth:
      serviceId: fenjin-cloud-oauth2
      path: /auth/**
      strip-prefix: true
      sensitiveHeaders: "*"

security:
  oauth2:
    resource:
#      user-info-uri:  http://192.168.110.9:7050/user
      user-info-uri:  http://localhost:${server.port}/auth/api/user
      prefer-token-info: false
#      loadBalanced: true
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
      client-id: web

info:
  app.name: fenjin-cloud-zuul-gateway
  company.name: www.fenjin.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$